<?php

defined( 'LL' ) || exit;

$links = [
    [
        'service_name' => 'GitHub',
        'link_label'   => 'GitHub',
        'link_url'     => '#',
        'button_class' => 'button-github',
        'icon_file'    => 'github.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
    [
        'service_name' => 'REPLACEME1',
        'link_label'   => 'REPLACEME2',
        'link_url'     => '#',
        'button_class' => 'REPLACEME3',
        'icon_file'    => 'REPLACEME4.svg',
    ],
];

