<?php

defined( 'LL' ) || exit;

$links = [
    [
        'service_name' => 'GitHub',
        'link_label'   => 'GitHub',
        'link_url'     => '#',
        'button_class' => 'button-github',
        'icon_file'    => 'github.svg',
    ],
    [
        'service_name' => 'Twitter',
        'link_label'   => 'Twitter',
        'link_url'     => '#',
        'button_class' => 'button-twit',
        'icon_file'    => 'twitter.svg',
    ],
    [
        'service_name' => 'Instagram',
        'link_label'   => 'Instagram',
        'link_url'     => '#',
        'button_class' => 'button-instagram',
        'icon_file'    => 'instagram.svg',
    ],
    [
        'service_name' => 'Facebook',
        'link_label'   => 'Find us on Facebook',
        'link_url'     => '#',
        'button_class' => 'button-faceb',
        'icon_file'    => 'facebook.svg',
    ],
    [
        'service_name' => 'Facebook Messenger',
        'link_label'   => 'Chat on Messenger',
        'link_url'     => '#',
        'button_class' => 'button-messenger',
        'icon_file'    => 'messenger.svg',
    ],
    [
        'service_name' => 'LinkedIn',
        'link_label'   => 'LinkedIn',
        'link_url'     => '#',
        'button_class' => 'button-linked',
        'icon_file'    => 'linkedin.svg',
    ],
    [
        'service_name' => 'YouTube',
        'link_label'   => 'YouTube',
        'link_url'     => '#',
        'button_class' => 'button-yt',
        'icon_file'    => 'youtube.svg',
    ],
    [
        'service_name' => 'Discord',
        'link_label'   => 'Discord',
        'link_url'     => '#',
        'button_class' => 'button-discord',
        'icon_file'    => 'discord.svg',
    ],
    [
        'service_name' => 'Twitch',
        'link_label'   => 'Twitch',
        'link_url'     => '#',
        'button_class' => 'button-twitch',
        'icon_file'    => 'twitch.svg',
    ],
    [
        'service_name' => 'Product Hunt',
        'link_label'   => 'Product Hunt',
        'link_url'     => '#',
        'button_class' => 'button-producthunt',
        'icon_file'    => 'producthunt.svg',
    ],
    [
        'service_name' => 'Snapchat',
        'link_label'   => 'Snapchat',
        'link_url'     => '#',
        'button_class' => 'button-snapchat',
        'icon_file'    => 'snapchat.svg',
    ],
    [
        'service_name' => 'Spotify',
        'link_label'   => 'Listen on Spotify',
        'link_url'     => '#',
        'button_class' => 'button-spotify',
        'icon_file'    => 'spotify.svg',
    ],
    [
        'service_name' => 'Spotify',
        'link_label'   => 'Listen on Spotify',
        'link_url'     => '#',
        'button_class' => 'button-spotify-alt',
        'icon_file'    => 'spotify-green.svg',
    ],
    [
        'service_name' => 'YouTube Music',
        'link_label'   => 'Listen on YouTube Music',
        'link_url'     => '#',
        'button_class' => 'button-yt',
        'icon_file'    => 'youtube-music.svg',
    ],
    [
        'service_name' => 'Apple Music',
        'link_label'   => 'Listen on Apple Music',
        'link_url'     => '#',
        'button_class' => 'button-apple-music',
        'icon_file'    => 'apple-music.svg',
    ],
    [
        'service_name' => 'Apple Music',
        'link_label'   => 'Listen on Apple Music',
        'link_url'     => '#',
        'button_class' => 'button-apple-music-alt',
        'icon_file'    => 'apple-music-white.svg',
    ],
    [
        'service_name' => 'Apple Podcasts',
        'link_label'   => 'Listen on Apple Podcasts',
        'link_url'     => '#',
        'button_class' => 'button-apple-podcasts',
        'icon_file'    => 'apple-podcasts.svg',
    ],
    [
        'service_name' => 'Apple Podcasts',
        'link_label'   => 'Listen on Apple Podcasts',
        'link_url'     => '#',
        'button_class' => 'button-apple-podcasts-alt',
        'icon_file'    => 'apple-podcasts-white.svg',
    ],
    [
        'service_name' => 'Google Podcasts',
        'link_label'   => 'Listen on Google Podcasts',
        'link_url'     => '#',
        'button_class' => 'button-google-podcasts',
        'icon_file'    => 'google-podcasts.svg',
    ],
    [
        'service_name' => 'Substack',
        'link_label'   => 'Subscribe on Substack',
        'link_url'     => '#',
        'button_class' => 'button-substack',
        'icon_file'    => 'substack.svg',
    ],
    [
        'service_name' => 'Clubhouse',
        'link_label'   => 'Clubhouse',
        'link_url'     => '#',
        'button_class' => 'button-clubhouse',
        'icon_file'    => 'clubhouse.svg',
    ],
    [
        'service_name' => 'Reddit',
        'link_label'   => 'Reddit',
        'link_url'     => '#',
        'button_class' => 'button-reddit',
        'icon_file'    => 'reddit.svg',
    ],
    [
        'service_name' => 'Mastodon',
        'link_label'   => 'Mastodon',
        'link_url'     => '#',
        'button_class' => 'button-mastodon',
        'icon_file'    => 'mastodon.svg',
    ],
    [
        'service_name' => 'Medium',
        'link_label'   => 'Medium',
        'link_url'     => '#',
        'button_class' => 'button-medium',
        'icon_file'    => 'medium.svg',
    ],
    [
        'service_name' => 'Pinterest',
        'link_label'   => 'Follow on Pinterest',
        'link_url'     => '#',
        'button_class' => 'button-pinterest',
        'icon_file'    => 'pinterest.svg',
    ],
    [
        'service_name' => 'TikTok',
        'link_label'   => 'TikTok',
        'link_url'     => '#',
        'button_class' => 'button-tiktok',
        'icon_file'    => 'tiktok.svg',
    ],
    [
        'service_name' => 'Email',
        'link_label'   => 'hello@littlelink.io',
        'link_url'     => '#',
        'button_class' => 'button-default',
        'icon_file'    => 'email.svg',
    ],
    [
        'service_name' => 'Email',
        'link_label'   => 'hello@littlelink.io',
        'link_url'     => '#',
        'button_class' => 'button-default',
        'icon_file'    => 'email_alt.svg',
    ],
    [
        'service_name' => 'Blog',
        'link_label'   => 'Blog',
        'link_url'     => '#',
        'button_class' => 'button-default',
        'icon_file'    => 'blog.svg',
    ],
    [
        'service_name' => 'SoundCloud',
        'link_label'   => 'SoundCloud',
        'link_url'     => '#',
        'button_class' => 'button-soundcloud',
        'icon_file'    => 'soundcloud.svg',
    ],
    [
        'service_name' => 'Figma',
        'link_label'   => 'Figma',
        'link_url'     => '#',
        'button_class' => 'button-figma',
        'icon_file'    => 'figma.svg',
    ],
    [
        'service_name' => 'Kit',
        'link_label'   => 'Kit',
        'link_url'     => '#',
        'button_class' => 'button-kit',
        'icon_file'    => 'kit.svg',
    ],
    [
        'service_name' => 'Telegram',
        'link_label'   => 'Telegram',
        'link_url'     => '#',
        'button_class' => 'button-telegram',
        'icon_file'    => 'telegram.svg',
    ],
    [
        'service_name' => 'LittleLink',
        'link_label'   => 'LittleLink',
        'link_url'     => '#',
        'button_class' => 'button-default',
        'icon_file'    => 'littlelink.svg',
    ],
    [
        'service_name' => 'Trello',
        'link_label'   => 'Trello',
        'link_url'     => '#',
        'button_class' => 'button-trello',
        'icon_file'    => 'trello.svg',
    ],
    [
        'service_name' => 'Notion',
        'link_label'   => 'Notion',
        'link_url'     => '#',
        'button_class' => 'button-notion',
        'icon_file'    => 'notion.svg',
    ],
    [
        'service_name' => 'Kickstarter',
        'link_label'   => 'Kickstarter',
        'link_url'     => '#',
        'button_class' => 'button-kickstarter',
        'icon_file'    => 'kickstarter.svg',
    ],
    [
        'service_name' => 'Etsy',
        'link_label'   => 'Etsy',
        'link_url'     => '#',
        'button_class' => 'button-etsy',
        'icon_file'    => 'etsy.svg',
    ],
    [
        'service_name' => 'Tumblr',
        'link_label'   => 'Tumblr',
        'link_url'     => '#',
        'button_class' => 'button-tumb',
        'icon_file'    => 'tumblr.svg',
    ],
    [
        'service_name' => 'Steam',
        'link_label'   => 'Steam',
        'link_url'     => '#',
        'button_class' => 'button-steam',
        'icon_file'    => 'steam.svg',
    ],
    [
        'service_name' => 'Strava',
        'link_label'   => 'Strava',
        'link_url'     => '#',
        'button_class' => 'button-strava',
        'icon_file'    => 'strava.svg',
    ],
    [
        'service_name' => 'Vimeo',
        'link_label'   => 'Vimeo',
        'link_url'     => '#',
        'button_class' => 'button-vimeo',
        'icon_file'    => 'vimeo.svg',
    ],
    [
        'service_name' => 'PayPal',
        'link_label'   => 'PayPal',
        'link_url'     => '#',
        'button_class' => 'button-paypal',
        'icon_file'    => 'paypal.svg',
    ],
    [
        'service_name' => 'WhatsApp',
        'link_label'   => 'WhatsApp',
        'link_url'     => '#',
        'button_class' => 'button-whatsapp',
        'icon_file'    => 'whatsapp.svg',
    ],
    [
        'service_name' => 'Untappd',
        'link_label'   => 'Untappd',
        'link_url'     => '#',
        'button_class' => 'button-untappd',
        'icon_file'    => 'untappd.svg',
    ],
    [
        'service_name' => 'Wordpress',
        'link_label'   => 'Wordpress',
        'link_url'     => '#',
        'button_class' => 'button-wordpress',
        'icon_file'    => 'wordpress.svg',
    ],
    [
        'service_name' => 'Goodreads',
        'link_label'   => 'Goodreads',
        'link_url'     => '#',
        'button_class' => 'button-goodreads',
        'icon_file'    => 'goodreads.svg',
    ],
    [
        'service_name' => 'Skoob',
        'link_label'   => 'Skoob',
        'link_url'     => '#',
        'button_class' => 'button-skoob',
        'icon_file'    => 'skoob.svg',
    ],
    [
        'service_name' => 'GitLab',
        'link_label'   => 'GitLab',
        'link_url'     => '#',
        'button_class' => 'button-gitlab',
        'icon_file'    => 'gitlab.svg',
    ],
    [
        'service_name' => 'xing',
        'link_label'   => 'Xing',
        'link_url'     => '#',
        'button_class' => 'button-xing',
        'icon_file'    => 'xing.svg',
    ],
    [
        'service_name' => 'Bandcamp',
        'link_label'   => 'Bandcamp',
        'link_url'     => '#',
        'button_class' => 'button-bandcamp',
        'icon_file'    => 'bandcamp.svg',
    ],
    [
        'service_name' => 'Patreon',
        'link_label'   => 'Patreon',
        'link_url'     => '#',
        'button_class' => 'button-patreon',
        'icon_file'    => 'patreon.svg',
    ],
    [
        'service_name' => 'Signal',
        'link_label'   => 'Signal',
        'link_url'     => '#',
        'button_class' => 'button-signal',
        'icon_file'    => 'signal.svg',
    ],
    [
        'service_name' => 'Apple App Store',
        'link_label'   => 'Apple App Store',
        'link_url'     => '#',
        'button_class' => 'button-appstore',
        'icon_file'    => 'appstore.svg',
    ],
    [
        'service_name' => 'Google Play Store',
        'link_label'   => 'Google Play Store',
        'link_url'     => '#',
        'button_class' => 'button-playstore',
        'icon_file'    => 'playstore.svg',
    ],
    [
        'service_name' => 'Amazon',
        'link_label'   => 'Amazon',
        'link_url'     => '#',
        'button_class' => 'button-amazon',
        'icon_file'    => 'amazon.svg',
    ],
    [
        'service_name' => 'Venmo',
        'link_label'   => 'Venmo',
        'link_url'     => '#',
        'button_class' => 'button-venmo',
        'icon_file'    => 'venmo.svg',
    ],
    [
        'service_name' => 'Cash App',
        'link_label'   => 'Cash App Dollar',
        'link_url'     => '#',
        'button_class' => 'button-cashapp',
        'icon_file'    => 'cashapp_dollar.svg',
    ],
    [
        'service_name' => 'Cash App',
        'link_label'   => 'Cash App Pound',
        'link_url'     => '#',
        'button_class' => 'button-cashapp',
        'icon_file'    => 'cashapp_pound.svg',
    ],
    [
        'service_name' => 'Cash App',
        'link_label'   => 'Cash App Bitcoin',
        'link_url'     => '#',
        'button_class' => 'button-cashapp',
        'icon_file'    => 'cashapp_btc.svg',
    ],
    [
        'service_name' => 'dev.to',
        'link_label'   => 'dev.to',
        'link_url'     => '#',
        'button_class' => 'button-dev-to',
        'icon_file'    => 'dev_to.svg',
    ],
    [
        'service_name' => 'Redbubble',
        'link_label'   => 'Redbubble',
        'link_url'     => '#',
        'button_class' => 'button-redbubble',
        'icon_file'    => 'redbubble.svg',
    ],
    [
        'service_name' => 'Only Fans',
        'link_label'   => 'OnlyFans (18+)',
        'link_url'     => '#',
        'button_class' => 'button-onlyfans',
        'icon_file'    => 'onlyfans.svg',
    ],
    [
        'service_name' => 'Web',
        'link_label'   => 'Website',
        'link_url'     => '#',
        'button_class' => 'button-web',
        'icon_file'    => 'web.svg',
    ],
    [
        'service_name' => 'Buy Me a Coffee',
        'link_label'   => 'Buy Me a Coffee',
        'link_url'     => '#',
        'button_class' => 'button-coffee',
        'icon_file'    => 'coffee.svg',
    ],
    [
        'service_name' => 'Ko-fi',
        'link_label'   => 'Ko-fi',
        'link_url'     => '#',
        'button_class' => 'button-ko-fi',
        'icon_file'    => 'ko-fi.svg',
    ],
    [
        'service_name' => 'VRChat',
        'link_label'   => 'VRChat',
        'link_url'     => '#',
        'button_class' => 'button-vrchat',
        'icon_file'    => 'vrchat.svg',
    ],
    [
        'service_name' => 'Threema',
        'link_label'   => 'Threema',
        'link_url'     => '#',
        'button_class' => 'button-threema',
        'icon_file'    => 'threema.svg',
    ],
    [
        'service_name' => 'Flickr',
        'link_label'   => 'Flickr',
        'link_url'     => '#',
        'button_class' => 'button-flickr',
        'icon_file'    => 'flickr.svg',
    ],
    [
        'service_name' => 'Letterboxd',
        'link_label'   => 'Letterboxd',
        'link_url'     => '#',
        'button_class' => 'button-letterboxd',
        'icon_file'    => 'letterboxd.svg',
    ],
    [
        'service_name' => 'hashnode',
        'link_label'   => 'Hashnode',
        'link_url'     => '#',
        'button_class' => 'button-hashnode',
        'icon_file'    => 'hashnode.svg',
    ],
    [
        'service_name' => 'Google Scholar',
        'link_label'   => 'Google Scholar',
        'link_url'     => '#',
        'button_class' => 'button-google-scholar',
        'icon_file'    => 'google_scholar.svg',
    ],
    [
        'service_name' => 'Post.',
        'link_label'   => 'Post.',
        'link_url'     => '#',
        'button_class' => 'button-post-news',
        'icon_file'    => 'post.news.png',
    ],
    [
        'service_name' => 'Unsplash',
        'link_label'   => 'Unsplash',
        'link_url'     => '#',
        'button_class' => 'button-unsplash',
        'icon_file'    => 'unsplash.svg',
    ],
];

